In [25]:
import google.generativeai as genai

genai.configure(api_key= 'AIzaSyDBECQnpdlHjyw0m90b8nMRBsA_oaE0WXU')
model = genai.GenerativeModel('gemini-1.5-pro-latest')

In [26]:
input_string = """
You are a data scientist working on a relation extraction task. Please do the following task and do not give output in the markdown format.One sample in relation extraction datasets consists of a relation, a context, a pair of head and tail entities in the context.The head entity has the relation with the tail entity.
Relation "person countries of residence" means a person is living in a country.
Here is an example:
Relation: person countries of residence
Context: iran 's top nuclear negotiator , ali larijani , was asked by state tv whether the country had started converting into gas a second batch of uranium , as it had planned to do at its isfahan nuclear facility .
Head Entity: ali larijani
Tail Entity: iran
Please generate 5 diversity samples (must have full : Relation , Context , Head Entity , Tail Entity) like the above example for the relation "person countries of residence":"""

In [27]:
generation_config = {
  "temperature": 0.0,
  "response_mime_type": "text/plain",
}

In [28]:
response = model.generate_content(input_string,generation_config=generation_config)

In [29]:
response.text

'Relation: person countries of residence\nContext: After fleeing the war in syria , the family settled in jordan , where they have been living for the past five years .\nHead Entity: the family\nTail Entity: jordan\n\nRelation: person countries of residence\nContext: Elon musk , the ceo of tesla and spacex , recently relocated to texas from california .\nHead Entity: Elon musk\nTail Entity: texas\n\nRelation: person countries of residence\nContext: Although she was born in argentina , she has lived in spain for most of her life and now considers madrid her home .\nHead Entity: she\nTail Entity: spain\n\nRelation: person countries of residence\nContext: My grandparents immigrated to canada from ireland in the 1950s and built a new life for themselves in toronto .\nHead Entity: My grandparents\nTail Entity: canada\n\nRelation: person countries of residence\nContext: The author , who currently resides in japan , draws inspiration for his novels from the rich cultural heritage of the count

In [21]:
import json

res = json.loads(response.text) 
res

[{'Relation': 'person countries of residence',
  'Context': 'russian president vladimir putin signed a decree on wednesday to expedite russian passports to residents of two regions of eastern ukraine , a move that could presage a russian military advance .',
  'Head Entity': 'vladimir putin',
  'Tail Entity': 'russia'},
 {'Relation': 'person countries of residence',
  'Context': 'in february 2021 , meghan markle accused the british royal family of racism .',
  'Head Entity': 'meghan markle',
  'Tail Entity': 'britain'},
 {'Relation': 'person countries of residence',
  'Context': 'during a visit to kyiv on saturday , british prime minister boris johnson announced a new package of military aid for ukraine .',
  'Head Entity': 'boris johnson',
  'Tail Entity': 'britain'},
 {'Relation': 'person countries of residence',
  'Context': 'the agreement was signed by chinese foreign minister wang yi and his solomon islands counterpart , jeremiah manele .',
  'Head Entity': 'jeremiah manele',
  'T

In [4]:
import torch

# Example input tensors
logits = torch.tensor([[-0.5, -1.2, -0.3], [-0.4, -0.9, -0.7]])
logits_des = torch.tensor([[0.8, 0.3, 0.5], [0.6, 0.2, 0.4]])

# Compute ranks for each score
logits_ranks = torch.argsort(torch.argsort(-logits, dim=1), dim=1) + 1
logits_des_ranks = torch.argsort(torch.argsort(-logits_des, dim=1), dim=1) + 1

In [5]:
logits_ranks

tensor([[2, 3, 1],
        [1, 3, 2]])

In [6]:
logits_des_ranks

tensor([[1, 3, 2],
        [1, 3, 2]])

In [42]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.cluster import KMeans
from sklearn.preprocessing import normalize


In [43]:
a = torch.rand(30,50)
rep_des = a
# Convert tensor to NumPy array
rep_des_np = rep_des.numpy()

# Normalize the vectors
rep_des_normalized = normalize(rep_des_np, norm='l2')

# Perform K-means clustering using cosine similarity
n_clusters = 3  # Change this to the desired number of clusters
kmeans = KMeans(n_clusters=n_clusters, random_state=0)
kmeans.fit(rep_des_normalized)

# Get the cluster labels
labels = kmeans.labels_

print("Cluster labels:", labels)

Cluster labels: [2 1 1 2 1 1 1 2 1 1 1 2 2 1 2 2 0 1 2 0 2 1 1 2 2 1 1 2 1 1]


In [45]:
type(kmeans.labels_.tolist())

list

In [37]:
from sklearn.cluster import KMeans

# Cluster the data with cosine distance using KMeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(a)


KMeans(n_clusters=3)

In [25]:
a[0]

tensor([0.2257, 0.3688, 0.8992, 0.4987, 0.4675, 0.8211, 0.7156, 0.8139, 0.4498,
        0.6110, 0.2493, 0.6990, 0.1948, 0.8486, 0.4983, 0.1436, 0.2679, 0.5593,
        0.6725, 0.7391, 0.0697, 0.3444, 0.4573, 0.5085, 0.0620, 0.3303, 0.8928,
        0.0603, 0.9179, 0.5863, 0.7030, 0.5874, 0.7911, 0.8091, 0.8917, 0.3379,
        0.9122, 0.6400, 0.5674, 0.6467, 0.5646, 0.5021, 0.5333, 0.0516, 0.8233,
        0.9104, 0.5385, 0.9345, 0.3581, 0.1843])

In [26]:
cos_sim = nn.CosineSimilarity()
cos_sim(a,a[0])

tensor([1.0000, 0.7975, 0.7243, 0.7325, 0.7432, 0.8249, 0.6834, 0.7717, 0.7952,
        0.7842, 0.7661, 0.8095, 0.7511, 0.8013, 0.8192, 0.8407, 0.7913, 0.7689,
        0.7466, 0.7789, 0.7336, 0.8441, 0.7926, 0.7837, 0.7693, 0.7748, 0.7852,
        0.7891, 0.7850, 0.7421])

In [27]:
def _cosine_similarity( x1, x2):
        '''
        input: x1 (B, H), x2 (N, H) ; N is the number of relations
        return: (B, N) 
        '''
        b = x1.size()[0]
        cos = nn.CosineSimilarity(dim=1)
        sim = []
        for i in range(b):
            sim_i = cos(x2, x1[i])
            sim.append(torch.unsqueeze(sim_i, 0))
        sim = torch.cat(sim, 0)
        return sim

In [28]:
sim = _cosine_similarity(a,a)

In [31]:
_, top_k_index  = torch.topk(sim, 5, dim=1)

In [35]:
top_k_index.shape
# drop first column
top_k_index = top_k_index[:,1:]

In [36]:
top_k_index

tensor([[21, 15,  5, 14],
        [11, 21, 27,  0],
        [ 8, 28, 15, 14],
        [27, 15, 17,  2],
        [11,  7, 23, 25],
        [ 0, 25, 15, 11],
        [ 9, 26, 19, 14],
        [16,  4, 11,  8],
        [ 2, 15, 25, 14],
        [14, 21, 26,  6],
        [23, 11, 26,  1],
        [23,  1,  0,  4],
        [25, 15, 26, 24],
        [21, 14, 29,  0],
        [ 9,  0, 26, 22],
        [27,  0, 23,  8],
        [29,  7, 20, 13],
        [28, 21,  3,  8],
        [14,  8, 22, 15],
        [28,  9, 15, 23],
        [16, 14,  7,  4],
        [ 9,  0, 13, 17],
        [14, 11,  0, 27],
        [11, 15, 28,  4],
        [16,  0, 15,  8],
        [ 8,  4, 12, 13],
        [ 9, 14, 16, 23],
        [15,  3,  1, 21],
        [19, 17,  2, 23],
        [16, 13, 21, 26]])

In [33]:
top_k_index[0][1:]

tensor([21, 15,  5, 14])

In [23]:
_

tensor([[1.0000, 0.8584],
        [1.0000, 0.8617],
        [1.0000, 0.8617]])